plugins:
  - jekyll-feed
  - jekyll-sitemap
title: Tagaroggu
email: taga@myself.com
twitter_username: tagaroggu
github_username:  tagaroggu
author:
  twitter: tagaroggu
url: "https://tagaroggu.github.io"
base_url: "/"
