plugins:
  - jekyll-feed
  - jekyll-sitemap
author:
  twitter: tagaroggu
url: "https://tagaroggu.github.io"
defaults:
  -
    scope:
      path: ""
      type: "posts"
    value:
      layouts: "post"
