plugins:
  - jekyll-feed
  - jekyll-sitemap
title: Tagaroggu
description: Personal website
email: taga@myself.com
twitter_username: tagaroggu
github_username:  tagaroggu
author:
  twitter: tagaroggu
url: "https://tagaroggu.github.io"
base_url: "/"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
  - scope:
      path: ""
    values:
      layout: "default"
